baseURL = 'https://komidan.github.io/'
title = 'komidan'

[locale]
  language = 'en-US'

[params]
  author = "komidan"

  [[params.social]]
    name = "github"
    url = "https://github.com/komidan"

  [[params.social]]
    name = "youtube"
    url = "https://youtube.com/@komidan_"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[markup]
  [markup.highlight]
    style = "gruvbox"
    lineNos = true
    codeFences = true
    noClasses = false
